# Generated by Django 2.0.4 on 2018-04-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('query_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'query_table',
            },
        ),
    ]
