# Generated by Django 2.0.4 on 2018-04-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('size', models.IntegerField()),
                ('download_url', models.TextField()),
                ('media', models.FileField(null=True, upload_to='uploads/')),
            ],
            options={
                'db_table': 'audio_table',
            },
        ),
    ]
